name: pos_universal_printer_example
description: Contoh penggunaan plugin pos_universal_printer untuk mencetak
  struk dan label.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  pos_universal_printer: ^0.2.9
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - assets/images/akib.png