name: pos_universal_printer_ios
description: Implementasi iOS untuk pos_universal_printer.
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  pos_universal_printer: ^0.2.9

flutter:
  plugin:
    implements: pos_universal_printer
    platforms:
      ios:
        pluginClass: PosUniversalPrinterIosPlugin
