name: pos_universal_printer_ios
description: Implementasi iOS untuk pos_universal_printer.
version: 0.1.0
homepage: https://github.com/fadhilmuhaimin/pos_universal_printer
repository: https://github.com/fadhilmuhaimin/pos_universal_printer

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  pos_universal_printer: ^0.2.10

flutter:
  plugin:
    implements: pos_universal_printer
    platforms:
      ios:
        pluginClass: PosUniversalPrinterIosPlugin
