name: pos_universal_printer
description: A Flutter plugin for printing POS receipts and labels on various thermal printers. Multi-role routing with Bluetooth & TCP support, custom sticker API with 4 complexity levels.
version: 0.2.6
homepage: https://github.com/fadhilmuhaimin/pos_universal_printer
repository: https://github.com/fadhilmuhaimin/pos_universal_printer/tree/main/packages/pos_universal_printer
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.10.0
  collection: ^1.17.0
  async: ^2.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        default_package: pos_universal_printer_android
      ios:
        default_package: pos_universal_printer_ios