name: pos_universal_printer
description: >-
  Plugin inti untuk pos_universal_printer yang menyediakan API publik
  berbasis Dart untuk mencetak struk dan label ESC/POS, TSPL, dan CPCL.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.10.0
  collection: ^1.17.0
  async: ^2.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        default_package: pos_universal_printer_android
      ios:
        default_package: pos_universal_printer_ios